# Generated by Django 4.2.2 on 2023-06-19 11:12

import cars_universe.web.models.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EnginePart', 'EnginePart'), ('OTHER', 'OTHER')], max_length=10)),
                ('brand', models.CharField(max_length=30)),
                ('brand_for', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='mediafiles/', validators=[cars_universe.web.models.models.validate_image])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cars_brand', models.CharField(choices=[('Audi', 'Audi'), ('Bmw', 'Bmw'), ('Vw', 'Vw'), ('Opel', 'Opel'), ('Ford', 'Ford'), ('Other', 'Other')], max_length=5)),
                ('photo', models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='mediafiles/', validators=[cars_universe.web.models.models.validate_image])),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=40)),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACCESSORIES', 'ACCESSORIES'), ('TOOLS', 'TOOLS')], max_length=11)),
                ('brand', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='mediafiles/', validators=[cars_universe.web.models.models.validate_image])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='web.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Audi', 'Audi'), ('Bmw', 'Bmw'), ('Vw', 'Vw'), ('Opel', 'Opel'), ('Ford', 'Ford'), ('Other', 'Other')], max_length=5)),
                ('photo', models.ImageField(blank=True, help_text='Maximum file size allowed is 5Mb', null=True, upload_to='mediafiles/', validators=[cars_universe.web.models.models.validate_image])),
                ('made_date', models.IntegerField(default=2005)),
                ('hp', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
