# Generated by Django 4.2.2 on 2023-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_likecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
