# Generated by Django 4.2.2 on 2023-06-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='orderr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_partss', to='web.order'),
        ),
        migrations.AddField(
            model_name='tool',
            name='orderr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_toolss', to='web.order'),
        ),
    ]
